site_name: UCLightcommands Hackathon
site_description: UCL Photonics Society x Thorlabs UK Hackathon
site_url: https://ucl-photonics-society.github.io/UCLightcommands/
repo_url: https://github.com/UCL-Photonics-Society/UCLightcommands

theme:
  name: material
  palette:
    - scheme: default
      primary: custom
      accent: custom
  logo: resources/logos/logo_purple.png
  favicon: resources/logos/logo_purple.png
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - toc.integrate

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - md_in_html
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Home: index.md
  - Phase 1:
      - Overview: phase1/overview.md
      - Prerequisites: phase1/prerequisites.md
      - Tasks: phase1/tasks.md
      - Final Report: phase1/final-report.md
  - Phase 2:
      - Overview: phase2/overview.md
      - Tasks: phase2/tasks.md
  - Phase 3:
      - Overview: phase3/overview.md
  - Photos:
      - Phase 1: photos/phase1.md
      - Phase 2: photos/phase2.md
      - Phase 3: photos/phase3.md
